### ISSUE TITLE
swift-im 4.0rc2 compilation error 

### ISSUE THREAD

**Issue by Fisiu** [swift/swift#94]
I tried to build swift 4.0rc2 however I receive error during combining license files.

```
[   45s] + cd swift-4.0rc2
[   45s] + scons V=1 Swift Swiften swiften_dll=1 test=none optimize=1 qt5=1 -j4
[   45s] scons: Reading SConscript files ...
(...)
[   67s]   Projects: Limber Slimber Swift Swiften
[   67s] 
[   67s]   XML Parsers: Expat
[   67s]   TLS Support: OpenSSL
[   67s]   DNSSD Support: Avahi
[   67s] 
[   67s] scons: done reading SConscript files.
[   67s] scons: Building targets ...
[   67s] g++ -o Swift/Controllers/AdHocController.o -c -std=c++11 -Wextra -Wall -Wnon-virtual-dtor -Wundef -Wold-style-cast -Wno-long-long -Woverloaded-virtual -Wfloat-equal -Wredundant-decls -Wno-unknown-pragmas -Wlogical-op -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fPIC -O2 -g -fPIC -DSWIFT_EXPERIMENTAL_FT -DSWIFT_EXPERIMENTAL_FT -DSWIFT_EXPERIMENTAL_FT -I. -I. -I. Swift/Controllers/AdHocController.cpp
(...)
[  252s] g++ -o Swift/Controllers/XMPPURIController.o -c -std=c++11 -Wextra -Wall -Wnon-virtual-dtor -Wundef -Wold-style-cast -Wno-long-long -Woverloaded-virtual -Wfloat-equal -Wredundant-decls -Wno-unknown-pragmas -Wlogical-op -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fPIC -O2 -g -fPIC -DSWIFT_EXPERIMENTAL_FT -DSWIFT_EXPERIMENTAL_FT -DSWIFT_EXPERIMENTAL_FT -I. -I. -I. Swift/Controllers/XMPPURIController.cpp
[  256s] Creating 'Swift/QtUI/COPYING'
[  256s] scons: *** [Swift/QtUI/COPYING] UnicodeEncodeError : 'ascii' codec can't encode character u'\xe7' in position 73: ordinal not in range(128)
[  256s] Traceback (most recent call last):
[  256s]   File "/usr/lib/python2.7/site-packages/SCons/Action.py", line 1197, in execute
[  256s]     result = self.execfunction(target=target, source=rsources, env=env)
[  256s]   File "/home/abuild/rpmbuild/BUILD/swift-4.0rc2/BuildTools/SCons/Tools/textfile.py", line 116, in _action
[  256s]     fd.write(_do_subst(s, subs))
[  256s] UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 73: ordinal not in range(128)
[  260s] scons: building terminated because of errors.
```

**Comment by tfar** [comment]
@Fisiu Thanks for verifying that it's fixed now. Will close this ticket.
